### ISSUE TITLE
Kreator misji

### ISSUE THREAD

**Issue by azaran1234** [blackuGT/Space-Next-Application#9]
Proszę o dodanie w informacjach podstawowych w liście rozwijanej "Pojazdy" firmy SpaceX rakiet: 
- Falcon 1
- Falcon 9 v1.0
- Falcon 9 v1.1
- Falcon 9 v1.2
- Falcon Heavy

**Comment by blackuGT** [comment]
Zostaną dodane na produkcji dzisiaj tj. 31.08.2020 o godz. 23:59.

**Comment by blackuGT** [comment]
Gotowe. Falcon 9 v1.2 istniał, jako block 5, dodano dopisek FT - Full Thrust.

**Comment by azaran1234** [comment]
Faktycznie, pisałem z marszu...
